import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient()

const Home: NextPage = ({ settings }: any) => {
    return (
        <div>
			<Head>
				<title>Dependency</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			{
				// @ts-ignore
				settings.map((setting) => (
					<div>{setting.name}</div>
				))
			}

        </div>
    );
};

export const getServerSideProps: GetServerSideProps = async () => {
	const settings = await prisma.settings.findMany();

	return {
		props: {
			settings
		}
	}
}

export default Home;
